ventes_tickets/Controllers/PDVController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ventes_tickets.Models;

namespace ventes_tickets.Controllers
{
    [Authorize]
    public class PDVController : Controller
    {
        private ventesContainer db = new ventesContainer();

        //
        // GET: /PDV/

        public ActionResult Index()
        {
            return View(db.Point_de_venteSet.ToList());
        }

        //
        // GET: /PDV/Details/5

        public ActionResult Details(int id = 0)
        {
            Point_de_vente point_de_vente = db.Point_de_venteSet.Find(id);
            if (point_de_vente == null)
            {
                return HttpNotFound();
            }
            return View(point_de_vente);
        }

        //
        // GET: /PDV/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /PDV/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Point_de_vente point_de_vente)
        {
            if (ModelState.IsValid)
            {
                db.Point_de_venteSet.Add(point_de_vente);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(point_de_vente);
        }

        //
        // GET: /PDV/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Point_de_vente point_de_vente = db.Point_de_venteSet.Find(id);
            if (point_de_vente == null)
            {
                return HttpNotFound();
            }
            return View(point_de_vente);
        }

        //
        // POST: /PDV/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Point_de_vente point_de_vente)
        {
            if (ModelState.IsValid)
            {
                db.Entry(point_de_vente).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(point_de_vente);
        }

        //
        // GET: /PDV/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Point_de_vente point_de_vente = db.Point_de_venteSet.Find(id);
            if (point_de_vente == null)
            {
                return HttpNotFound();
            }
            return View(point_de_vente);
        }

        //
        // POST: /PDV/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Point_de_vente point_de_vente = db.Point_de_venteSet.Find(id);
            db.Point_de_venteSet.Remove(point_de_vente);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

ventes_tickets/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ventes_tickets.Models;

namespace ventes_tickets.Controllers
{
    public class TicketController : Controller
    {
        private ventesContainer db = new ventesContainer();

        //
        // GET: /Ticket/

        public ActionResult Index()
        {
            try
            {
                ViewData["role"] = db.UserProfile.SingleOrDefault(e => e.UserName == User.Identity.Name).role;
            }
            catch { }
            string role = db.UserProfile.SingleOrDefault(e => e.UserName == User.Identity.Name).role;
            if (String.Equals(role, "Admin"))
                return View(db.TicketsSet.ToList());
            else
                return View(db.TicketsSet.Where(e => e.UserProfile.UserName == User.Identity.Name).ToList());
        }

        //
        // GET: /Ticket/Details/5

        public ActionResult Details(int id = 0)
        {
            Tickets tickets = db.TicketsSet.Find(id);
            if (tickets == null)
            {
                return HttpNotFound();
            }
            return View(tickets);
        }

        //
        // GET: /Ticket/Create

        public ActionResult Create()
        {

            ViewData["type"] = db.Type_ticketSet.ToList();
            ViewData["PDV"] = db.Point_de_venteSet.ToList();
            ViewData["date"] = DateTime.Now.ToString("dd/MM/yyyy");
            
            return View();
        }

        //
        // POST: /Ticket/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Tickets tickets)
        {
            if (ModelState.IsValid)
            {
                tickets.Point_de_venteSet = db.Point_de_venteSet.SingleOrDefault(e => e.Id == tickets.Point_de_vente_Id);
                tickets.Type_ticketSet = db.Type_ticketSet.SingleOrDefault(e => e.Id == tickets.Type_ticket_Id);
                tickets.UserProfile = db.UserProfile.SingleOrDefault(e => e.UserName == User.Identity.Name);
                tickets.UserProfile_UserId = db.UserProfile.SingleOrDefault(e => e.UserName == User.Identity.Name).UserId;
                db.TicketsSet.Add(tickets);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tickets);
        }


        //demande de suppression
        public ActionResult Demande_supp(int id = 0)
        {
            Tickets tickets = db.TicketsSet.Find(id);
            tickets.a_supp = 1;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        //
        // GET: /Ticket/Edit/5

        public ActionResult Edit(int id = 0)
        {

            ViewData["type"] = db.Type_ticketSet.ToList();
            ViewData["PDV"] = db.Point_de_venteSet.ToList();
            Tickets tickets = db.TicketsSet.Find(id);
            if (tickets == null)
            {
                return HttpNotFound();
            }
            return View(tickets);
        }

        //
        // POST: /Ticket/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Tickets tickets)
        {
            if (ModelState.IsValid)
            {
                tickets.Point_de_venteSet = db.Point_de_venteSet.SingleOrDefault(e => e.Id == tickets.Point_de_vente_Id);
                tickets.Type_ticketSet = db.Type_ticketSet.SingleOrDefault(e => e.Id == tickets.Type_ticket_Id);
                tickets.UserProfile = db.UserProfile.SingleOrDefault(e => e.UserName == User.Identity.Name);
                tickets.UserProfile_UserId = db.UserProfile.SingleOrDefault(e => e.UserName == User.Identity.Name).UserId;
                
                db.Entry(tickets).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tickets);
        }

        //
        // GET: /Ticket/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Tickets tickets = db.TicketsSet.Find(id);
            if (tickets == null)
            {
                return HttpNotFound();
            }
            return View(tickets);
        }

        //
        // POST: /Ticket/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tickets tickets = db.TicketsSet.Find(id);
            db.TicketsSet.Remove(tickets);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

ventes_tickets/Controllers/TypeTicketController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ventes_tickets.Models;

namespace ventes_tickets.Controllers
{
    [Authorize]
    public class TypeTicketController : Controller
    {
        private ventesContainer db = new ventesContainer();

        //
        // GET: /TypeTicket/

        public ActionResult Index()
        {
            return View(db.Type_ticketSet.ToList());
        }

        //
        // GET: /TypeTicket/Details/5

        public ActionResult Details(int id = 0)
        {
            Type_ticket type_ticket = db.Type_ticketSet.Find(id);
            if (type_ticket == null)
            {
                return HttpNotFound();
            }
            return View(type_ticket);
        }

        //
        // GET: /TypeTicket/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /TypeTicket/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Type_ticket type_ticket)
        {
            if (ModelState.IsValid)
            {
                db.Type_ticketSet.Add(type_ticket);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(type_ticket);
        }

        //
        // GET: /TypeTicket/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Type_ticket type_ticket = db.Type_ticketSet.Find(id);
            if (type_ticket == null)
            {
                return HttpNotFound();
            }
            return View(type_ticket);
        }

        //
        // POST: /TypeTicket/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Type_ticket type_ticket)
        {
            if (ModelState.IsValid)
            {
                db.Entry(type_ticket).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(type_ticket);
        }

        //
        // GET: /TypeTicket/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Type_ticket type_ticket = db.Type_ticketSet.Find(id);
            if (type_ticket == null)
            {
                return HttpNotFound();
            }
            return View(type_ticket);
        }

        //
        // POST: /TypeTicket/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Type_ticket type_ticket = db.Type_ticketSet.Find(id);
            db.Type_ticketSet.Remove(type_ticket);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

ventes_tickets/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ventes_tickets.Models;

namespace ventes_tickets.Controllers
{
    [Authorize]
    public class UsersController : Controller
    {
        private ventesContainer db = new ventesContainer();

        //
        // GET: /Users/

        public ActionResult Index()
        {
            return View(db.UserProfile.ToList());
        }
        public ActionResult menu()
        {
            try
            {
                ViewData["role"] = db.UserProfile.SingleOrDefault(e => e.UserName == User.Identity.Name).role;
            }
            catch { }
            return PartialView();
        }

        //
        // GET: /Users/Details/5

        public ActionResult Details(int id = 0)
        {
            UserProfile userprofile = db.UserProfile.Find(id);
            if (userprofile == null)
            {
                return HttpNotFound();
            }
            return View(userprofile);
        }

        //
        // GET: /Users/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Users/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(UserProfile userprofile)
        {
            if (ModelState.IsValid)
            {
                db.UserProfile.Add(userprofile);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(userprofile);
        }

        //
        // GET: /Users/Edit/5

        public ActionResult Edit(int id = 0)
        {
            UserProfile userprofile = db.UserProfile.Find(id);
            if (userprofile == null)
            {
                return HttpNotFound();
            }
            return View(userprofile);
        }

        //
        // POST: /Users/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UserProfile userprofile)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userprofile).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(userprofile);
        }

        //
        // GET: /Users/Delete/5

        public ActionResult Delete(int id = 0)
        {
            UserProfile userprofile = db.UserProfile.Find(id);
            if (userprofile == null)
            {
                return HttpNotFound();
            }
            return View(userprofile);
        }

        //
        // POST: /Users/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UserProfile userprofile = db.UserProfile.Find(id);
            db.UserProfile.Remove(userprofile);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

ventes_tickets/Views/Users/Create.cshtml
@model ventes_tickets.Models.UserProfile

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>UserProfile</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UserName)
            @Html.ValidationMessageFor(model => model.UserName)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ventes_tickets/Views/Users/Delete.cshtml
@model ventes_tickets.Models.UserProfile

@{
    ViewBag.Title = "Delete";
}

<h2>Supprimer</h2>

<h3>Etes vous sure de bien vouloir supprimer l'element suivant ?</h3>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Supprimer" class="btn btn-danger "/> |
        @Html.ActionLink("Annuler", "Index", null, new { @class = "btn btn-primary" })
    </p>
}

ventes_tickets/Views/Users/Details.cshtml
@model ventes_tickets.Models.UserProfile

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>UserProfile</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserName)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.UserId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ventes_tickets/Views/Users/Edit.cshtml
@model ventes_tickets.Models.UserProfile

@{
    ViewBag.Title = "Edit";
}

<h2>Editer l'utilisateur</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>

        @Html.HiddenFor(model => model.UserId)

        
        <div class="editor-label">
            Nom complet
        </div>
        <div class="form-group">
            @Html.TextBoxFor(model => model.nom_complet, new { @class = "form-control " })
            @Html.ValidationMessageFor(model => model.nom_complet)
        </div>
        <div class="editor-label">
            Role
        </div>
        <div class="form-group">
            
            @Html.DropDownListFor(model => model.role, new SelectList(
                  new List<Object>{ 
                       new { value = "Admin" , text = "Administrateur"  },
                       new { value = "Agent" , text = "Responsable des ventes" }
                    },
                  "value",
               "text"), new { @class = "form-control " })
            
        </div>

        <div class="editor-label">
            Adresse
        </div>
        <div class="form-group">
            @Html.TextBoxFor(model => model.adresse, new { @class = "form-control " })
            @Html.ValidationMessageFor(model => model.adresse)
        </div>


        <p>
            <input type="submit" value="Enregistrer" class="btn-lg btn-success" />
        </p>
    </fieldset>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ventes_tickets/Views/Users/Index.cshtml
@model IEnumerable<ventes_tickets.Models.UserProfile>

@{
    ViewBag.Title = "Index";
}

<h2>Gestion des utilisateurs</h2>


<table class="table table-bordered table-condensed table-striped table-hover table-responsive">
    <tr>
        <th>
            Login
        </th>
        <th>
            Nom complet
        </th>
        <th>
            Role
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nom_complet)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.role)
            </td>
            <td>
                <span class="glyphicon glyphicon-edit"></span> @Html.ActionLink("Editer", "Edit", new { id = item.UserId }) |
                <span class="glyphicon glyphicon-remove"></span> @Html.ActionLink("Supprimer", "Delete", new { id = item.UserId })
            </td>
        </tr>
    }

</table>

ventes_tickets/Views/Users/menu.cshtml
<div class="panel panel-default">
    <div class="panel-heading">
        <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                <span class="glyphicon glyphicon-folder-close">
                </span> Ventes
            </a>
        </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in">
        <div class="panel-body">
            <table class="table">
                <tr>
                    <td>
                        <span class="glyphicon glyphicon-pencil text-primary"></span> @Html.ActionLink("Ajouter une vente", "Create", "Ticket")
                    </td>
                </tr>
                <tr>
                    <td>
                        <span class="glyphicon glyphicon-flash text-success"></span> @Html.ActionLink("Gèrer les ventes", "Index", "Ticket")
                    </td>
                </tr>

            </table>
        </div>
    </div>
</div>

@if (String.Equals(ViewData["role"], "Admin") )
{ 
<div class="panel panel-default">
    <div class="panel-heading">
        <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
                <span class="glyphicon glyphicon-th">
                </span> Référentiel
            </a>
        </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse">
        <div class="panel-body">
            <table class="table">
                <tr>
                    <td>
                        @Html.ActionLink("Ajouter un types de produit", "Create", "TypeTicket")
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.ActionLink("Gèrer les types de produits", "Index", "TypeTicket")
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.ActionLink("Ajouter un points de vente", "Create", "PDV")
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.ActionLink("Gèrer les points de vente", "Index", "PDV")
                    </td>
                </tr>

            </table>
        </div>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">
        <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
                <span class="glyphicon glyphicon-user">
                </span> Administration
            </a>
        </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse">
        <div class="panel-body">
            <table class="table">
                <tr>
                    <td>
                        @Html.ActionLink("Ajouter un utilisateur", "Register", "Account")
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.ActionLink("Gestion des utilisateurs", "Index", "Users")
                    </td>
                </tr>

            </table>
        </div>
    </div>
</div>
}
else{
<div class="panel panel-default">
    <div class="panel-heading">
        <h4 class="panel-title">
            <a data-toggle="collapse" data-parent="#accordion" href="#collapseFour">
                <span class="glyphicon glyphicon-file">
                </span> Rapports
            </a>
        </h4>
    </div>
    <div id="collapseFour" class="panel-collapse collapse">
        <div class="panel-body">
            <table class="table">
                <tr>
                    <td>
                        <span class="glyphicon glyphicon-usd"></span> <a href="~/Content/repports/1.xlsx">Rapport par date</a>
                    </td>
                </tr>
                <tr>
                    <td>
                        <span class="glyphicon glyphicon-alert"></span> <a href="~/Content/repports/2.xlsx">Rapport par type</a>
                    </td>
                </tr>
                <tr>
                    <td>
                        <span class="glyphicon glyphicon-tasks"></span> <a href="~/Content/repports/3.xlsx">Rapport par point de vente</a>
                    </td>
                </tr>

            </table>
        </div>
    </div>
</div>
}